const mongoose = require('mongoose');

const InterviewScheduleSchema = new mongoose.Schema({
  // Link to the candidate
  applicantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Applicants',
    required: true
  },
  
  // Link to the specific job position
  jobId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Job',
    required: true
  },

  // The final assigned time from your search utility
  startTime: {
    type: Date,
    required: true
  },
  
  endTime: {
    type: Date,
    required: true
  },

  // The Google Meet link generated by the API
  googleMeetLink: {
    type: String,
    required: true
  },

  // Crucial: The unique ID from Google Calendar
  // You need this if you want to update/delete the event later
  calendarEventId: {
    type: String,
    required: true,
    unique: true
  },

  // Track the status of the interview itself
  status: {
    type: String,
    enum: ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED'],
    default: 'SCHEDULED'
  },

  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('InterviewSchedule', InterviewScheduleSchema);