// server/models/Job.js
const mongoose = require('mongoose');

const jobSchema = new mongoose.Schema({
  // The title of the position (e.g., "Full Stack Developer")
  title: {
    type: String,
    required: true,
    trim: true
  },
  
  // The link/path generated by Multer when the Admin uploads the JD
  jdFileUrl: {
    type: String,
    required: true 
  },
  
  // The live count of how many candidates have applied
  applicantCount: {
    type: Number,
    default: 0 
  },
  
  // Crucial for your Cron Job and LangGraph state logic
  status: {
    type: String,
    enum: ['OPEN', 'WAITING', 'READY_FOR_REVIEW', 'NOTIFIED_ADMIN', 'CLOSED'],
    default: 'OPEN'
  },
  
  // Used by your Cron Job to calculate if 7 days have passed
  createdAt: {
    type: Date,
    default: Date.now 
  }
});

// Create and export the model
module.exports = mongoose.model('Job', jobSchema);