const { google } = require('googleapis');
const { bulkScheduleSearch } = require('../utility_functions/scheduler.js'); 
const InterviewSchedule = require("../../Mongo schemas/InterviewSchedule.js");

const schedulingNode = async (state) => {
    // Note: We use the keys exactly as defined in your RecruiterState
    const { shortlistedCandidates, jobId, jdText, adminRefreshToken } = state;
    const jobTitle = state.jobTitle || "Software Engineer"; // Fallback if not in state

    const auth = new google.auth.OAuth2(
        process.env.GOOGLE_CLIENT_ID,
        process.env.GOOGLE_CLIENT_SECRET
    );
    auth.setCredentials({ refresh_token: adminRefreshToken });
    const calendar = google.calendar({ version: 'v3', auth });

    try {
        console.log(`[Scheduling] Processing ${shortlistedCandidates.length} candidates...`);

        // 1. Find available slots using the utility
        const candidatesWithTimes = await bulkScheduleSearch(auth, shortlistedCandidates);

        // This array will hold the updated objects to save back into 'shortlistedCandidates'
        const updatedShortlist = [];

        for (const candidate of candidatesWithTimes) {
            const event = {
                summary: `Interview: ${candidate.name} | ${jobTitle}`,
                description: `Interview for Job ID: ${jobId}. Generated by AI Recruiter.`,
                start: { 
                    dateTime: candidate.startTime.toISOString(), 
                    timeZone: 'UTC' 
                }, 
                end: { 
                    dateTime: candidate.endTime.toISOString(), 
                    timeZone: 'UTC' 
                },
                attendees: [{ email: candidate.email }],
                conferenceData: { 
                    createRequest: { 
                        requestId: `meet_${candidate.applicantId}_${Date.now()}`,
                        conferenceSolutionKey: { type: 'hangoutsMeet' }
                    } 
                }
            };

            const response = await calendar.events.insert({
                calendarId: 'primary',
                resource: event,
                conferenceDataVersion: 1, 
            });

            const meetLink = response.data.hangoutLink;
            const eventId = response.data.id;

            // 2. Persist to the InterviewSchedule collection
            await InterviewSchedule.create({
                applicantId: candidate.applicantId,
                jobId: jobId,
                startTime: candidate.startTime,
                endTime: candidate.endTime,
                googleMeetLink: meetLink,
                calendarEventId: eventId,
                status: 'SCHEDULED'
            });

            // 3. Prepare the updated object for the State
            updatedShortlist.push({
                ...candidate,
                meetLink: meetLink,
                interviewTime: candidate.startTime,
                calendarEventId: eventId
            });
        }

        

        // 4. Return the updated keys to the RecruiterState
        // We map our results back to 'shortlistedCandidates' so the graph 'remembers' them
        return { 
            ...state, 
            shortlistedCandidates: updatedShortlist, 
            applicationStatus: "SCHEDULED" 
        };

    } catch (error) {
        console.error("Scheduling Node Error:", error);
        return state; 
    }
};

module.exports = schedulingNode;